name: output information on issues
on:
  issues:
    types: [opened,edited,milestoned]
jobs:
  output_information:
    if: ${{ github.ref == "refs/heads/main" }}
    runs-on: ubuntu-latest
    steps:
      echo: "Deploying on $GITHUB_REF"
    